### ISSUE TITLE
Problem building ltc from source

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry-incubator/ltc#4]
Hi! Following [these][1] instructions got two errors.

```
$ go install github.com/cloudfoundry-incubator/ltc
package github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/Users/lexsys/code/ltc/ltc/Godeps/_workspace/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
	/Users/lexsys/go/src/github.com/docker/docker/autogen/dockerversion
package github.com/docker/docker/nat: cannot find package "github.com/docker/docker/nat" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/docker/docker/nat (from $GOROOT)
	/Users/lexsys/code/ltc/ltc/Godeps/_workspace/src/github.com/docker/docker/nat (from $GOPATH)
	/Users/lexsys/go/src/github.com/docker/docker/nat
``` 

[1]: https://github.com/cloudfoundry-incubator/lattice-release/tree/v0.6.0#install-ltc

**Comment by davidwadden** [comment]
Did you follow the [development instructions](https://github.com/cloudfoundry-incubator/lattice-release#development) in [cloudfoundry-incubator/lattice-release](https://github.com/cloudfoundry-incubator/lattice-release)?  This sets up the `GOPATH` as the `lattice-release` folder with our vendored dependencies beneath it.

`ltc` is not `go get`-able since one of our dependencies [docker/docker](https://github.com/docker/docker/) is also not `go get`-able.  The error looks as though you're pulling in a newer version of the docker dependency than we work with presently.

@davidwadden

**Comment by sclevine** [comment]
Did you happen to clone lattice-release without `--recursive`? As David mentioned, it seems like you have the wrong version of docker checked out.

If that's the case, running `git submodule update --init --recursive` in lattice-release may fix your issue.

**Comment by lexsys27** [comment]
Thank you for quick response!

Actually, I didn't get from documentation that I need `cloudfoundry-incubator/lattice-release` to build `ltc ` cli, as it has its own repo. I just cloned `cloudfoundry-incubator/ltc` and do `go get`.

Now I managed to compile `ltc` from   `cloudfoundry-incubator/lattice-release`.

Maybe it is more convenient to copy dev docs and dependencies to `ltc` repo?

**Comment by davidwadden** [comment]
We discussed this some recently when we decided to discontinue Godeps [[#101770536](https://www.pivotaltracker.com/story/show/101770536)].  We used to provide Godeps but it was difficult reconciling that with tracking upstream dependencies ([diego-release](https://github.com/cloudfoundry-incubator/diego-release)) that was prone to being forgotten/done wrong manually or required complicated logic from CI to maintain it.

Maybe most notably, docker/docker#10922 also poses an issue with Godeps.  I found trying to bump docker past [**v1.5.0**](https://github.com/docker/docker/releases/tag/v1.5.0) in the past wouldn't work because a) it doesn't compile until you run the docker autogen and b) `godep save` won't work if the branch is dirty (from the autogen).  This was part of why we moved to managing with submodules.

However, I'll have a conversation whether there's a way to support an `ltc`-only developer.
